# Generated by Django 3.1 on 2020-08-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimePersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=20)),
                ('finishedEpisodes', models.IntegerField()),
                ('endDate', models.DateField()),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Anime',
        ),
    ]
