# Generated by Django 3.1 on 2020-08-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0003_animepersonal_animeglobalid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeInfoPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('directedBy', models.CharField(max_length=250)),
                ('producedBy', models.CharField(max_length=250)),
                ('writtenBy', models.CharField(max_length=250)),
                ('musicBy', models.CharField(max_length=250)),
                ('studio', models.CharField(max_length=250)),
                ('licensedBy', models.CharField(max_length=250)),
                ('originalNetwork', models.CharField(max_length=250)),
                ('originalRun', models.CharField(max_length=250)),
                ('episodes', models.IntegerField()),
            ],
        ),
    ]
