# Generated by Django 3.1 on 2020-09-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0005_animepersonal_animeinfopersonalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeinfopersonal',
            name='userId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animepersonal',
            name='userId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
