# Generated by Django 3.1.1 on 2020-09-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0006_auto_20200915_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animeinfopersonal',
            name='userId',
        ),
        migrations.AlterField(
            model_name='animepersonal',
            name='animeGlobalId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='animepersonal',
            name='animeInfoPersonalId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='animepersonal',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
