# Generated by Django 3.1.1 on 2020-09-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0007_auto_20200926_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeinfopersonal',
            name='directedBy',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='animeinfopersonal',
            name='licensedBy',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='animeinfopersonal',
            name='musicBy',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='animeinfopersonal',
            name='originalNetwork',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='animeinfopersonal',
            name='originalRun',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='animeinfopersonal',
            name='producedBy',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='animeinfopersonal',
            name='studio',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='animeinfopersonal',
            name='writtenBy',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
