# Generated by Django 3.1.1 on 2020-10-02 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0010_auto_20200930_1745'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MangaInfoPersonal',
        ),
        migrations.DeleteModel(
            name='MangaPersonal',
        ),
    ]
