# Generated by Django 3.1.1 on 2020-10-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0011_auto_20201003_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeinfopersonal',
            name='englishNetwork',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
