# Generated by Django 3.1 on 2020-08-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WikiScraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeglobal',
            name='directedBy',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='animeglobal',
            name='licensedBy',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='animeglobal',
            name='musicBy',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='animeglobal',
            name='originalNetwork',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='animeglobal',
            name='originalRun',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='animeglobal',
            name='producedBy',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='animeglobal',
            name='studio',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='animeglobal',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='animeglobal',
            name='writtenBy',
            field=models.CharField(max_length=250),
        ),
    ]
