# Generated by Django 3.1.1 on 2020-09-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WikiScraper', '0002_auto_20200825_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeglobal',
            name='directedBy',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='animeglobal',
            name='licensedBy',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='animeglobal',
            name='musicBy',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='animeglobal',
            name='originalNetwork',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='animeglobal',
            name='originalRun',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='animeglobal',
            name='producedBy',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='animeglobal',
            name='studio',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='animeglobal',
            name='writtenBy',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
