# Generated by Django 3.1.1 on 2020-09-30 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WikiScraper', '0004_mangaglobal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mangaglobal',
            old_name='Volumes',
            new_name='volumes',
        ),
    ]
