# Generated by Django 3.1.1 on 2020-10-03 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WikiScraper', '0005_auto_20200930_1744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MangaGlobal',
        ),
    ]
