# Generated by Django 3.1.1 on 2020-10-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WikiScraper', '0006_delete_mangaglobal'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeglobal',
            name='englishNetwok',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
